pipeline {
    agent any
    environment {
        GC = credentials('github-spring-cicd') //생성하세여
        GIT_REPO = 'MZ-personal-project-server'
        GIT_USERNAME = 'ehszl409'
        TAG_VERSION = "v1.0.$BUILD_NUMBER"

        DS = credentials('docker-secret')
    }
    triggers {
        githubPush()
    }
    stages {
        stage('maven build, test, packaging(war)') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17'
                    reuseNode true
                    registryUrl 'https://index.docker.io/v1/'
                    registryCredentialsId 'docker-hub'
                }
            }
                steps {
                    sh 'mvn clean install'
                }     
        }
        stage('sonarQube Testing') {
            steps {
                script {
                    withSonarQubeEnv('sonarproject') {
                        sh """
                            docker run --rm \
                                -e SONAR_HOST_URL=$SONAR_HOST_URL \
                                -e SONAR_LOGIN=$SONAR_AUTH_TOKEN \
                                -e SONAR_SCANNER_OPTS='-Dsonar.projectKey=sonarproject -Dsonar.java.binaries=./target -Dsonar.verbose=true' \
                                -v /var/lib/docker/volumes/jenkins-volume/_data/workspace/spring-cicd:/usr/src \
                                sonarsource/sonar-scanner-cli
                        """
                    }
                }
                timeout(time: 3, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }        
        }
        stage('github create release') {
            steps {
                script { def response = sh(script: """                    
                        curl -sSL \
                              -X POST \
                              -H "Accept: application/vnd.github+json" \
                              -H "Authorization: Bearer ${GC_PSW}" \
                              -H "X-GitHub-Api-Version: 2022-11-28" \
                              https://api.github.com/repos/${GIT_USERNAME}/${GIT_REPO}/releases \
                              -d '{
                                      "tag_name":"${TAG_VERSION}",
                                      "target_commitish":"main",
                                      "name":"${TAG_VERSION}",
                                      "body":"Description of the release",
                                      "draft":false,
                                      "prerelease":false,
                                      "generate_release_notes":false
                                    }'
                    """, returnStdout: true)

                    def json = readJSON text: "$response"
                    def id = json.id

                    sh "mv target/demo-0.0.1-SNAPSHOT.war ${GIT_REPO}-${TAG_VERSION}.war"
                        
                    sh """
                        curl -sSL \
                            -X POST \
                            -H "Accept: application/vnd.github+json" \
                            -H "Authorization: Bearer ${GC_PSW}" \
                            -H "X-GitHub-Api-Version: 2022-11-28" \
                            -H "Content-Type: application/octet-stream" \
                            "https://uploads.github.com/repos/${GIT_USERNAME}/${GIT_REPO}/releases/${id}/assets?name=${GIT_REPO}-${TAG_VERSION}.war" \
                            --data-binary "@${GIT_REPO}-${TAG_VERSION}.war"
                    """
                    sh "mv ${GIT_REPO}-${TAG_VERSION}.war root.war"
                }
            }
        }     
        stage('dockerfile build'){
            steps{
                script{
                    // Docker hub 에 로그인 하기 위해 사용
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub') {
                        // Dockerfile 로 이미지 생성 
                        // docker.build("태그명", "Dockerfile 경로") docker pipeline 설치 후 사용 가능
                        docker.build("ehszl409/personal-prj-tomcat:${TAG_VERSION}", "--no-cache ./")    
                    }
                }
            }
        }
        stage('dockerHub Push'){
            steps{
                script{
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub'){
                        def img = docker.image("ehszl409/personal-prj-tomcat:${TAG_VERSION}")
                        img.push("${TAG_VERSION}")
                        img.push('latest')
                    }
                }
            }
        }
        stage('dockerRegi push'){
            steps{
                sh 'docker -H tcp://192.168.10.1:2375 ps -a'
                sh "docker -H tcp://192.168.10.1:2375 tag ehszl409/personal-prj-tomcat:${TAG_VERSION} localhost:5000/tomcat:${TAG_VERSION}"
                sh "docker -H tcp://192.168.10.1:2375 push localhost:5000/tomcat:${TAG_VERSION}"
                sh "docker -H tcp://192/168/10/1:2375 rmi ehszl409/personal-prj-tomcat:${TAG_VERSION}"
            }
        }
        stage ('k8s deploy'){
            steps{
                script {
                    sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"'
                    sh 'chmod +x kubectl'
                    withKubeConfig([credentialsId: 'admin.conf', serverUrl: 'https://kube-controller:6443'])
                    { 
                        sh './kubectl apply -f deploy.yaml'
                    }
                }
            }
        }
    }
}
